behaviors:
  RocketLanding:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 4.16e-5
      beta: 2.06e-3
      epsilon: 0.124
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 100000000
    time_horizon: 64
    summary_freq: 10000
environment_parameters:
    rocket_landing_env_param_1:
        curriculum:
            - name: niveau13
              value: 550
    rocket_landing_env_param_2:
        curriculum:
            - name: niveau7
              value: 90
    rocket_landing_env_param_3:
        curriculum:
            - name: niveau7
              value: 90
    rocket_landing_env_param_4:
        curriculum:
            - name: niveau6
              value: 1
    rocket_landing_env_param_5:
        curriculum:
            - name: niveau1
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.025
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 5
            - name: niveau2
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.05
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 6
            - name: niveau3
              value: 7
    rocket_landing_env_param_6:
        curriculum:
            - name: niveau1
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.10
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 2.5
            - name: niveau2
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.125
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 2.25
            - name: niveau3
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.15
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 2.0
            - name: niveau4
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.1725
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 1.5
            - name: niveau5
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.20
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 1.0
            - name: niveau6
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.225
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 0.7
            - name: niveau7
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.25
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 0.4
            - name: niveau8
              value: 0.2