behaviors:
  RocketLanding:
    trainer_type: ppo
    hyperparameters:
      batch_size: 64
      buffer_size: 1024
      learning_rate: 3.0e-4
      beta: 0.01
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    behavioral_cloning:
      demo_path: Unity/SN20/Assets/Demonstrations/Demo3D.demo
      strength: 0.5
      steps: 500000
      batch_size: 64
      num_epoch: 3
      samples_per_update: 512
    max_steps: 100000000
    time_horizon: 64
    summary_freq: 10000
environment_parameters:
    rocket_landing_env_param_1:
        curriculum:
            - name: niveau1
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.05
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 50
            - name: niveau2
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.10
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 60
            - name: niveau2
              completion_criteria:
                measure: progress
                behavior: RocketLanding
                threshold: 0.15
                min_lesson_length: 100
                signal_smoothing: true
                require_reset: true
              value: 70
            - name: niveau3
              value: 90